<?php

/**
 * Implements hook_block().
 */
function asc_social_media_d6_block($op = 'list', $delta = 0, $edit = array()) {
	switch ($op) {

		case 'list':
			$blocks['asc_socialmedia_sharing']['info'] = t('ASC Social Media Share');
			return $blocks;

		case 'view':
			if ($delta == 0) {
				$block['subject'] = t('Asc_social_media_d6 block 1 title');
				$vars = array(
					'url' => urlencode('http://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI']),
					'title' => urlencode(drupal_get_title()),
					'picture' => '',
					'description' => '',
				);
				$block['content'] = theme('asc_socialmedia_sharing', $vars);
			}
			return $block;
	}
}

/*
 * Implementation of hook_theme()
 */
function asc_socialmedia_theme() {
  return array(
    'asc_socialmedia_sharing' => array(
      'template' => 'asc_socialmedia_sharing',
    ),
  );
}

/**
 * Implements hook_init().
 */
function asc_social_media_d6_init() {
  drupal_add_css(drupal_get_path('module', 'asc_social_media_d6') . '/asc_socialmedia.css');
  drupal_add_js(drupal_get_path('module', 'asc_social_media_d6') . '/asc_socialmedia_sharing.js');
}